### ISSUE TITLE
https on heroku

### ISSUE THREAD

**Issue by trshafer** [Ephigenia/circleboard#1]
Hey foobugs,

the heroku app is blocked by chrome because socket.io is requesting an insecure connection: 
![screeenshot](https://cloud.githubusercontent.com/assets/135461/8012350/b0b20b98-0b75-11e5-8944-99db866b02c1.png)

The connection is started here: https://github.com/foobugs/circleboard/blob/master/www/main.coffee#L147

**Comment by Ephigenia** [comment]
Thanks for noticing. I will try to find a solution!

**Comment by Ephigenia** [comment]
@growlsworth how come that you where using "https" in the url? The link to the demo in the [README](https://github.com/foobugs/circleboard) is using "http" instead of "https".

None the less I have changed the code which connects to the socket.io instance so that is uses the protocol used in the document’s location - https should work now fine :) Hope you like the project.

**Comment by Ephigenia** [comment]
Please try and close the issue if it’s working for you :)

**Comment by trshafer** [comment]
Clicking the link on the readme redirects to https automatically. Maybe it's my https everywhere chrome extension. Also the demo now works over https. Thanks.

**Comment by Ephigenia** [comment]
@growlsworth the redirect is definitely created by the extension, so may happen that you have similar experiences on other websites that don’t use HTTP.

Glad to hear that everything works fine. Would be cool if you can post ideas or requirements if you have any.

**Comment by trshafer** [comment]
Hey @Ephigenia, 

The real dashboard that I want is:
1. what's on the remote repo
   - what's on master
   - other active branches
2. what's on ci
   - most recent master success
   - is a master build running
   - is the master build broken now
   - other branch status
3. what's on production
   - what's the current sha
   - is something deploying right now

All of these for different projects/applications.

I found circleboard when seeing if somebody already had a github/circle/heroku dashboard. I think other people might be interested in this type of dashboard if you want to expand circleboard further. But otherwise, don't have any current suggestions. Cheers.

**Comment by Ephigenia** [comment]
okay, thanks for the feedback :+1:
